name: SkWaze
author: Weefle
version: 3.0.3
description: The coolest Skript's addon
depends: [Skript]
softdepends: [BossBarAPI, Citizens, Builder, Constructor, LibsDisguises, ProtocolLib, HolographicDisplays, Netherboard]
main: fr.weefle.waze.Waze
api-version: 1.13
commands:
  packetmanager:
    description: Used to manage and monitor packets.
    aliases: [packetman,packetmonitor,packetmon]