name: SkWaze
author: Weefle
version: 2.2.7
description: The coolest Skript's addon
depends: [Skript]
softdepends: [BossBarAPI, Citizens, Builder, ProtocolLib, LibsDisguises, HolographicDisplays, Netherboard]
main: fr.weefle.waze.Waze
api-version: 1.13